# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optioncalc.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(937, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Compbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Compbutton.setGeometry(QtCore.QRect(460, 10, 191, 71))
        self.Compbutton.setObjectName("Compbutton")
        self.StPrice = QtWidgets.QTextEdit(self.centralwidget)
        self.StPrice.setGeometry(QtCore.QRect(9, 9, 191, 51))
        self.StPrice.setObjectName("StPrice")
        self.Strike = QtWidgets.QTextEdit(self.centralwidget)
        self.Strike.setGeometry(QtCore.QRect(10, 70, 191, 51))
        self.Strike.setObjectName("Strike")
        self.Days = QtWidgets.QTextEdit(self.centralwidget)
        self.Days.setGeometry(QtCore.QRect(10, 130, 191, 51))
        self.Days.setObjectName("Days")
        self.intrate = QtWidgets.QTextEdit(self.centralwidget)
        self.intrate.setGeometry(QtCore.QRect(10, 190, 191, 51))
        self.intrate.setObjectName("intrate")
        self.volatility = QtWidgets.QTextEdit(self.centralwidget)
        self.volatility.setGeometry(QtCore.QRect(460, 190, 191, 51))
        self.volatility.setObjectName("volatility")
        self.corp = QtWidgets.QTextEdit(self.centralwidget)
        self.corp.setGeometry(QtCore.QRect(10, 250, 191, 51))
        self.corp.setObjectName("corp")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 80, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 140, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 200, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 200, 81, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 260, 81, 21))
        self.label_6.setObjectName("label_6")
        self.dividend = QtWidgets.QTextEdit(self.centralwidget)
        self.dividend.setGeometry(QtCore.QRect(10, 310, 191, 51))
        self.dividend.setObjectName("dividend")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 310, 81, 21))
        self.label_7.setObjectName("label_7")
        self.optprice = QtWidgets.QTextEdit(self.centralwidget)
        self.optprice.setGeometry(QtCore.QRect(460, 260, 191, 51))
        self.optprice.setObjectName("optprice")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(670, 270, 81, 21))
        self.label_8.setObjectName("label_8")
        self.Delta1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Delta1.setGeometry(QtCore.QRect(10, 390, 191, 51))
        self.Delta1.setObjectName("Delta1")
        self.Theta1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Theta1.setGeometry(QtCore.QRect(250, 390, 191, 51))
        self.Theta1.setObjectName("Theta1")
        self.Vega1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Vega1.setGeometry(QtCore.QRect(490, 390, 191, 51))
        self.Vega1.setObjectName("Vega1")
        self.Gamma1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Gamma1.setGeometry(QtCore.QRect(730, 390, 191, 51))
        self.Gamma1.setObjectName("Gamma1")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 450, 81, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(320, 450, 81, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(540, 450, 81, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(770, 450, 81, 21))
        self.label_12.setObjectName("label_12")
        self.Compbutton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Compbutton_2.setGeometry(QtCore.QRect(460, 100, 191, 71))
        self.Compbutton_2.setObjectName("Compbutton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Compbutton.setText(_translate("MainWindow", "Compute Price"))
        self.label.setText(_translate("MainWindow", "Price"))
        self.label_2.setText(_translate("MainWindow", "Strike"))
        self.label_3.setText(_translate("MainWindow", "Days until Exp"))
        self.label_4.setText(_translate("MainWindow", "Int Rate"))
        self.label_5.setText(_translate("MainWindow", "Volatility"))
        self.label_6.setText(_translate("MainWindow", "Call or Put"))
        self.label_7.setText(_translate("MainWindow", "Dividend yield"))
        self.label_8.setText(_translate("MainWindow", "Option Price"))
        self.label_9.setText(_translate("MainWindow", "Delta"))
        self.label_10.setText(_translate("MainWindow", "Theta"))
        self.label_11.setText(_translate("MainWindow", "Vega"))
        self.label_12.setText(_translate("MainWindow", "Gamma"))
        self.Compbutton_2.setText(_translate("MainWindow", " Compute Vol"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

