# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optioncalc.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(937, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Compbutton = QtWidgets.QPushButton(self.centralwidget)
        self.Compbutton.setGeometry(QtCore.QRect(460, 90, 191, 71))
        self.Compbutton.setObjectName("Compbutton")
        self.Max = QtWidgets.QTextEdit(self.centralwidget)
        self.Max.setGeometry(QtCore.QRect(9, 9, 191, 51))
        self.Max.setObjectName("Max")
        self.Percentage = QtWidgets.QTextEdit(self.centralwidget)
        self.Percentage.setGeometry(QtCore.QRect(10, 70, 191, 51))
        self.Percentage.setObjectName("Percentage")
        self.OutWeight = QtWidgets.QTextEdit(self.centralwidget)
        self.OutWeight.setGeometry(QtCore.QRect(10, 130, 191, 51))
        self.OutWeight.setObjectName("OutWeight")
        self.OutWeight_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.OutWeight_2.setGeometry(QtCore.QRect(10, 190, 191, 51))
        self.OutWeight_2.setObjectName("OutWeight_2")
        self.OutWeight_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.OutWeight_3.setGeometry(QtCore.QRect(10, 250, 191, 51))
        self.OutWeight_3.setObjectName("OutWeight_3")
        self.OutWeight_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.OutWeight_4.setGeometry(QtCore.QRect(10, 310, 191, 51))
        self.OutWeight_4.setObjectName("OutWeight_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 80, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 140, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 200, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 260, 81, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 320, 81, 21))
        self.label_6.setObjectName("label_6")
        self.OutWeight_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.OutWeight_5.setGeometry(QtCore.QRect(10, 370, 191, 51))
        self.OutWeight_5.setObjectName("OutWeight_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 380, 81, 21))
        self.label_7.setObjectName("label_7")
        self.OutWeight_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.OutWeight_6.setGeometry(QtCore.QRect(460, 260, 191, 51))
        self.OutWeight_6.setObjectName("OutWeight_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(670, 270, 81, 21))
        self.label_8.setObjectName("label_8")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 440, 191, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(230, 440, 81, 21))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Compbutton.setText(_translate("MainWindow", "Compute"))
        self.label.setText(_translate("MainWindow", "Price"))
        self.label_2.setText(_translate("MainWindow", "Strike"))
        self.label_3.setText(_translate("MainWindow", "Exp Date"))
        self.label_4.setText(_translate("MainWindow", "Int Rate"))
        self.label_5.setText(_translate("MainWindow", "Volatility"))
        self.label_6.setText(_translate("MainWindow", "Call or Put"))
        self.label_7.setText(_translate("MainWindow", "Dividend yield"))
        self.label_8.setText(_translate("MainWindow", "Result"))
        self.label_9.setText(_translate("MainWindow", "Result requested"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

